apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  auth-api-port: "8000"
  server-port: "8083"
  todo-api-port: "8082"
  redis-host: "redis"
  redis-channel: "log_channel"
  zipkin-url: "http://zipkin:9411"
  prometheus-url: "http://prometheus:9090"
  grafana-url: "http://grafana:3000"
